name: Ziva Dynamics
favicon: null
layout_spectrum: 0.25852
typography_spectrum: 0.9169
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#939598'
    - '#1f3d7c'
    - '#00a2b1'
    - '#ffffff'
    - '#00ffff'
  brandStrength: 0.625
  lightness: 0
  saturation: 0.5
  rhythmicContrast: 0.25
purpose: []
