name: Ziva Dynamics
favicon: null
layout_spectrum: 0.7669604278635234
typography_spectrum: 0.6343425652012229
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.47904738783836365
  lightness: 0.5728967855684459
  saturation: 0.5751121041830629
  rhythmicContrast: 0.030732161831110716
purpose: []
