name: Ziva Dynamics
favicon: null
layout_spectrum: 0.49399
typography_spectrum: 0.9169
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#939598'
    - '#1f3d7c'
    - '#00a2b1'
    - '#ffffff'
    - '#00ffff'
  brandStrength: 0.6875
  lightness: 0.5728967855684459
  saturation: 0
  rhythmicContrast: 0.030732161831110716
purpose: []
